#!/bin/sh

# this will mock git commands by wrapping in-toto run with default arguments
if [ $1 == "tag" ]; then
  in-toto-run --step-name tag-webapp --key $KEY --products public src -- ${GIT} $@
else
  $GIT $@
fi