#!/bin/sh

# this will mock git commands by wrapping in-toto run with default arguments
command_name=$1
KEY=/home/santiago/Documents/p2017/in-toto-general/docker-demo/in-toto-metadata/santiago

in-toto-run --step-name tag-webapp --key $KEY --products public src -- /usr/bin/git $@ 
